Repository ca-cwds/case-management, pull requests merged in 2018-02, with the labels that each got.

#223 Allow dupe spec names only in diff branches
  .eslintrc-common.js
Labels: chore

#224 No color in output
  package.json
Labels: build

#217 Integrate Rails API with ArcGIS map feature
  app/javascript/_services/api/api.js
  app/javascript/_services/client/client.service.js
  app/javascript/dashboard/DashboardContainer.jsx
  app/javascript/placement/PlacementContainer.jsx
  app/javascript/placement/PlacementContainer.test.js
  app/javascript/placement/_components/filters/Filters.jsx
  app/javascript/placement/_components/placement-list/PlacementList.jsx
  app/javascript/placement/_components/placement-list/RelatedClientCard.jsx
  app/javascript/placement/_components/placement-list/RelatedClientCard.test.jsx
  app/javascript/placement/_components/placement-map/PlacementMap.jsx
  app/javascript/placement/_components/placement-map/PlacementMap.test.js
  config/feature.yml
  lib/addresses/address.rb
  lib/infrastructure/http_service.rb
  lib/placements/address_geo_provider.rb
  spec/lib/addresses/address_spec.rb
  spec/lib/addresses/geo_repository_spec.rb
  spec/lib/infrastructure/http_service_spec.rb
  spec/lib/placements/address_geo_provider_spec.rb
  spec/lib/placements/address_map_service_spec.rb
Labels: Feature

#233 Fixes and changes for finding placement tool
  app/javascript/_services/case/case.service.js
  app/javascript/_services/referral/referral.service.js
  app/javascript/dashboard/DashboardContainer.jsx
  docker-compose.yml
  lib/addresses/address_repository.rb
  lib/referrals/referral_repository.rb
  spec/lib/addresses/address_repository_spec.rb
  spec/lib/referrals/referral_repository_spec.rb
Labels: chore
